-- plugin manager
require('plugins-cfg.pm')
--
require('plugins-cfg.autopairs')
require('plugins-cfg.autosave')
require('plugins-cfg.bufferline')
require('plugins-cfg.cmp')
require('plugins-cfg.dap')
require('plugins-cfg.explorer')
require('plugins-cfg.golang')
require('plugins-cfg.lsp')
require('plugins-cfg.lspsaga')
require('plugins-cfg.lualine')
require('plugins-cfg.telescope')
require('plugins-cfg.theme')
require('plugins-cfg.toggleterm')
require('plugins-cfg.treesitter')
