#!/usr/bin/env bash

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# source the colors
if [ -f ${HOME}/.cache/wal/colors.sh ]; then
    . ${HOME}/.cache/wal/colors.sh
    #### BSPWM coloring ####
    bspc config active_border_color   "$color2"
    bspc config focused_border_color  "$color15"
    bspc config normal_border_color   "$color1"
    bspc config presel_feedback_color "$color1"
fi

#### MONITORS ####
bspc monitor eDP-1 -d 1 2 3 4 5

#### BSPWM configuration ####
bspc config border_width              1
bspc config focus_follows_pointer     true
bspc config window_gap                5
bspc config top_padding               24

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

