return {
	-- "olimorris/codecompanion.nvim",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"nvim-treesitter/nvim-treesitter",
	-- 	{
	-- 		"ellisonleao/dotenv.nvim",
	-- 		opts = {
	-- 			enable_on_load = true,
	-- 			file_name = vim.env.HOME .. "/devx-copilot.env",
	-- 		},
	-- 	},
	-- },
	-- opts = {
	-- 	strategies = {
	-- 		chat = {
	-- 			adapter = "devx",
	-- 		},
	-- 		cmd = {
	-- 			adapter = "devx",
	-- 		},
	-- 		inline = {
	-- 			adapter = "devx",
	-- 		},
	-- 	},
	-- 	opts = {
	-- 		language = "Russian",
	-- 	},
	-- 	adapters = {
	-- 		devx = function()
	-- 			return require("codecompanion.adapters").extend("openai_compatible", {
	-- 				env = {
	-- 					url = vim.env.DEVX_COPILOT_API_URL,
	-- 					api_key = vim.env.DEVX_COPILOT_API_KEY,
	-- 					models_endpoint = "/v1/models", -- optional: attaches to the end of the URL to form the endpoint to retrieve models
	-- 				},
	-- 				headers = {
	-- 					["Content-Type"] = "application/json",
	-- 					["Authorization"] = "Bearer ${api_key}",
	-- 					["X-Copilot-User-Token"] = "${api_key}",
	-- 					["X-Copilot-User-Agent"] = vim.env.DEVX_COPILOT_API_USER_AGENT,
	-- 				},
	-- 				schema = {
	-- 					model = {
	-- 						default = "claude-4-sonnet",
	-- 					},
	-- 				},
	-- 			})
	-- 		end,
	-- 	},
	-- }
}
