#!/usr/bin/env sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#### MONITORS ####

#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9


#### BSPWM configuration ####
#bspc config border_radius               8
#bspc config borderless_monocle          true
#bspc config bottom_padding              0
#bspc config click_to_focus              true
#bspc config focus_by_distance           true
#bspc config gapless_monocle             true
#bspc config history_aware_focus         true
#bspc config left_padding                0
#bspc config merge_overlapping_monitors  true
#bspc config pointer_action1             move
#bspc config pointer_action2             resize_side
#bspc config pointer_action3             resize_corner
#bspc config pointer_modifier            mod4
#bspc config remove_disabled_monitors    true
#bspc config right_padding               0
#bspc config single_monocle              false
#bspc config split_ratio                 0.50
bspc config border_width                3
bspc config focus_follows_pointer       true
bspc config top_padding                 24
bspc config window_gap                  15

#### BSPWM coloring ####
bspc config active_border_color         "#1e1e1e"
bspc config focused_border_color        "#5e81ac"
bspc config normal_border_color         "#4c566a"
bspc config presel_feedback_color       "#5e81ac"
bspc config urgent_border_color         "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

