require("user.paq")

-- require("user.null-ls")
require("user.autosave")
require("user.dap")
require("user.explorer")
require("user.golang")
require("user.lsp")
require("user.mini")
require("user.multicursors")
require("user.telescope")
require("user.terminal")
require("user.theme")
require("user.treesitter")
